---
- name: Deploy application to remote server
  hosts: all
  become: yes
  tasks:
    - name: Update apt repositories
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: yes

#This playbook:
#Updates the apt repositories.
#Installs the Nginx web server.
#Starts the Nginx service.
